# Numpy Revision Final notes

In [1]:
import numpy as np

##### Basic functions

In [2]:
# To print the version of NumPy
print(np.__version__)

1.18.1


In [4]:
# To create An Array in NumPy
myarr1 = np.array([65,12,49,38]) # we can also pass tuples,array,list in np.array() method
print(myarr1) # 1D Array

[65 12 49 38]


In [5]:
# To print size of An Array
print(myarr1.itemsize)

4


In [6]:
# To Sort the Array
print(np.sort(myarr1))

[12 38 49 65]


In [7]:
# To print the type of a Data Structure
print(type(myarr1))

<class 'numpy.ndarray'>


In [8]:
# To get the shape of an array i.e (row,column)
myarr1.shape

(4,)

In [9]:
# To print the data type of an array
myarr1.dtype

dtype('int32')

In [10]:
# To print the data type of an array
myarr1.dtype

dtype('int32')

In [11]:
# For Itreating 1D Array
for x in myarr1:
    print(x)

65
12
49
38


In [12]:
# To access the Element of An Array
myarr1[2]

49

In [13]:
# To change the data in an 1D array with its index
myarr1[3] = 27
myarr1

array([65, 12, 49, 27])

In [14]:
print(myarr1)
# To slice an 1D array acccording to its index
print(myarr1[0:2:1]) # array[start:stop:step] include elements according to stepping
print(myarr1[1:3]) # array[start:stop] include start index but skips the stop index

[65 12 49 27]
[65 12]
[12 49]


In [15]:
# To split an array in different size
newmyarr1 = np.array_split(myarr1,4) # np.array_split(arr,size) will split the array in required size
print(newmyarr1)
print(newmyarr1[0])
print(newmyarr1[1])
print(newmyarr1[2])
print(newmyarr1[3])

[array([65]), array([12]), array([49]), array([27])]
[65]
[12]
[49]
[27]


In [16]:
# To search for an element after sorting
print(np.searchsorted(myarr1,12)) # Print index of element entered
print(np.searchsorted(myarr1,38,side="right")) # Print index of element entered from right side
print(np.searchsorted(myarr1,65,side="left")) # Print index of element entered from left side

0
2
4


##### Basic Calculation

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [18]:
# For adding array
a + b

array([ 7,  9, 11, 13, 15])

In [19]:
# For subtracting array
a - b

array([-5, -5, -5, -5, -5])

In [20]:
# For multiplicating array
a * b

array([ 6, 14, 24, 36, 50])

In [21]:
# For deviding array
a / b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

##### Splitting and stacking Array

In [22]:
ar1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
np.stack((ar1,ar2)) # newarr = np.stack((arr1,arr2),axis=1) will stack two array across a new axis

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
# It will stack array across columns
np.hstack((ar1,ar2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [24]:
# It will stack array across row
np.vstack((ar1,ar2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [25]:
# It will stack array across height, which is same as depth
np.dstack((ar1,ar2))

array([[[ 1, 10],
        [ 2, 11],
        [ 3, 12]],

       [[ 4, 13],
        [ 5, 14],
        [ 6, 15]],

       [[ 7, 16],
        [ 8, 17],
        [ 9, 18]]])

###### dsplit only works on arrays of 3 or more dimensions

In [26]:
ar3 = np.arange(9).reshape(3,3)
print(ar3)
np.array_split(ar3,3) # For splitting array

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [27]:
# For splittig array across columns
np.hsplit(ar3,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [28]:
# For splitting array across column
np.vsplit(ar3,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

##### linspace Function in Numpy

In [29]:
# To print evenly spaced numbers between two given number np.linspace(num1,num2,spacing)
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

###### Basic 2D Functions

In [30]:
# To create an array with diffrent size like int8,int16,int32,int64
myarr2 = np.array([[33,46,89,182,195]],np.int32)
print(myarr2)

[[ 33  46  89 182 195]]


In [31]:
# To print the Dimension of an array
print(myarr2.ndim)

2


In [32]:
# To print the number of bytes in an array
myarr2.nbytes

20

In [33]:
# To get the shape of an array i.e (row,column)
myarr2.shape

(1, 5)

In [34]:
# To print the data type of an array
myarr2.dtype

dtype('int32')

In [35]:
# To print size of An Array
print(myarr2.itemsize)

4


In [36]:
# To access an element of an 2D Array with arr[row_index,col_index]
myarr2[0,3]

182

In [37]:
# # To change the data in an 2D array with its index
myarr2[0,3] = 18
myarr2

array([[ 33,  46,  89,  18, 195]])

In [38]:
# To slice an 2D array acccording to its index
print(myarr2[0,1:4]) # array[axis=0/1,start:stop:step] for 2D Arrays

[46 89 18]


##### Creating Higher Dimension Array

In [39]:
# To create an array with higher dimension
fivedimarr = np.array([1,2,3,4],ndmin=5)
print(fivedimarr)
# To print the Dimension of an array
print(fivedimarr.ndim)

[[[[[1 2 3 4]]]]]
5


###### Changing the DataType of an array

In [40]:
# Numpy has many DataTypes
# i - integer
# b - boolean
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

In [41]:
# To change the data type of an array
dtypearr = np.array([12,74,36,88,40,55],dtype="f")
print(dtypearr)
# To print the data type of an array
print(dtypearr.dtype)

[12. 74. 36. 88. 40. 55.]
float32


In [42]:
# To change the data type of an array
newarr = dtypearr.astype("i")
print(newarr)
# To print the data type of an array
print(newarr.dtype)

[12 74 36 88 40 55]
int32


In [43]:
# To change the data type of an array
floatarr = np.array([1.11,2.32,5.45,2.01])
print(floatarr)
# To print the data type of an array
print(floatarr.dtype)
intarr = floatarr.astype(int)
print(intarr)
# To print the data type of an array
print(intarr.dtype)

[1.11 2.32 5.45 2.01]
float64
[1 2 5 2]
int32


In [44]:
# To change the data type of an array
arr = np.array([1,0,3,5,0,1])
print(arr)
# To print the data type of an array
print(arr.dtype)
boolarr = arr.astype(bool)
print(boolarr)
# To print the data type of an array
print(boolarr.dtype)

[1 0 3 5 0 1]
int32
[ True False  True  True False  True]
bool


###### Different Ways to Iterate an Array

In [45]:
# To create an 2D array 
lstarr = np.array([[11,52,73],[94,85,56],[27,38,99]])
print(lstarr)

[[11 52 73]
 [94 85 56]
 [27 38 99]]


In [46]:
# To itreating an 2D Array
for x in lstarr:
    for y in x:
        print(y)

11
52
73
94
85
56
27
38
99


In [47]:
# To itreating an 2D Array using np.nditer(arr) function
for x in np.nditer(lstarr):
    print(x)

11
52
73
94
85
56
27
38
99


In [48]:
 # To itreating an 2D Array using np.nditer(arr) function with slicing
for x in np.nditer(lstarr[1,0:]):
    print(x)

94
85
56


In [49]:
 # By itreating an 2D Array using np.ndenumerate(arr) function to get values with their index
for x in np.ndenumerate(lstarr):
    print(x)

((0, 0), 11)
((0, 1), 52)
((0, 2), 73)
((1, 0), 94)
((1, 1), 85)
((1, 2), 56)
((2, 0), 27)
((2, 1), 38)
((2, 2), 99)


##### Concatenating Array

In [50]:
x = np.ones((3,3))
print(x)
y = np.identity(3)
print(y)
newarr1 = np.concatenate((x,y)) # For concatenating two array
print(newarr1)
newarr2 = np.concatenate((x,y),axis=1) # For concatenating two array along their axis either 0 or 1
print(newarr2)
newarr2 = np.concatenate((x,y),axis=0) # For concatenating two array along their axis either 0 or 1
print(newarr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### View and Copy of an Array

In [51]:
newlstarr = lstarr.copy() # arr.copy() saves the orignal array and makes changes to the copy of array
lstarr[1,0:1]= 66
print(lstarr)
print(newlstarr)
print(newlstarr.base) # arr.base returns None for arr.copy()

[[11 52 73]
 [66 85 56]
 [27 38 99]]
[[11 52 73]
 [94 85 56]
 [27 38 99]]
None


In [52]:
newlstarr = lstarr.view() # arr.view() creates a view of array and if changes are made into orignal array then it will reflected into the view of the array
lstarr[1,0:1]= 19
print(lstarr)
print(newlstarr)
print(newlstarr.base) # arr.base returns the orignal array for arr.view()

[[11 52 73]
 [19 85 56]
 [27 38 99]]
[[11 52 73]
 [19 85 56]
 [27 38 99]]
[[11 52 73]
 [19 85 56]
 [27 38 99]]


##### Different Arrays in Numpy

In [53]:
# To create an array with all elements as zero(0)
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
# To create an array with all elements as one(1)
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
# To create an array with all element as empty
empty = np.empty((3,3))
empty

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
# To create an array with all digonal elements as one(1)
idnt = np.identity(3)
idnt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
# To create an array with all digonal elements as specified
dig = np.diag((5,6,7))
dig

array([[5, 0, 0],
       [0, 6, 0],
       [0, 0, 7]])

##### arange Function of Numpy

In [58]:
# To print series of numbers starting with zero
rng = np.arange(15) 
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##### Reshaping an Array

In [61]:
# To create an array
myarr3 = np.array([[1,3,5],[7,9,11]])
myarr3

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [62]:
# To reshape an array in a valid dimension 
myarr3.reshape(3,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [63]:
# arr.reshape(-1) can also flatten the array
print(myarr3.reshape(-1))

[ 1  3  5  7  9 11]


##### reshape creates a view of an array, so arr.reshape().base returns the orignal array

In [64]:
# Because arr.reshape() is a view of an array, so arr.reshape().base returns the orignal array
myarr3.reshape(3,2).base

array([[ 1,  3,  5],
       [ 7,  9, 11]])

##### Flatenning an Array

In [65]:
# arr.ravel() is used for flattening an array
print(myarr3.ravel())

[ 1  3  5  7  9 11]


In [66]:
# To create an array
myarr4 = np.array([[2,4,6],[8,10,12],[14,16,18]])
# arr.ravel() is used for flattening an array
myarr4.ravel()

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

##### Operation according to the axis (1/0)

In [67]:
# For making sum of elements at axis=0
myarr4.sum(axis=0)

array([24, 30, 36])

In [68]:
# For making sum of elements at axis=1
myarr4.sum(axis=1)

array([12, 30, 48])

###### Transpose of an Array

In [69]:
# To transpose an array i.e (row changes to column) and (column changes to row)
myarr4.T

array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18]])

##### Iterating a 2D Flat Array

In [70]:
# To iterate an 2D Flat Array
myarr4.flat
for item in myarr4.flat:
    print(item)

2
4
6
8
10
12
14
16
18


##### argsort(), argmin(), argmax() Function on Array

In [71]:
# To print the Array
myarr4

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [72]:
# To get the index of maximum element in the array
myarr4.argmax()

8

In [73]:
# To get the index of minimum element in the array
myarr4.argmin()

0

In [74]:
# To get the index of maximum element in the array according to axis
myarr4.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [75]:
# To get the index of maximum element in the array according to axis
myarr4.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [76]:
# To get the index of minimum element in the array according to axis
myarr4.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [77]:
# To get the index of minimum element in the array according to axis
myarr4.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [78]:
# To sort the array and return the index of sorted array
myarr4.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [79]:
# To sort the array and return the index of sorted array according to axis
myarr4.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [80]:
# To sort the array and return the index of sorted array according to axis
myarr4.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

Basic Operation on Array##### 

In [81]:
# To find the maximum element present in the array
myarr4.max()

18

In [82]:
# To find the minimum element present in the array
myarr4.min()

2

In [83]:
# To sum up all the elements present in the array
myarr4.sum()

90

##### sqrt Function of Numpy

In [84]:
# To take the square root of an entire array
np.sqrt(myarr4)

array([[1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162],
       [3.74165739, 4.        , 4.24264069]])

##### std() Function of Numpy

In [85]:
# To take the Standard Derivation of an entire array
np.std(myarr4)

5.163977794943222

##### Adding Array

In [86]:
# To add two or more array with valid dimension
myarr4 + lstarr

array([[ 13,  56,  79],
       [ 27,  95,  68],
       [ 41,  54, 117]])

##### np.where() Function in Numpy

In [87]:
# To find the index of the element where the condition satisfies
np.where(myarr4>5)

(array([0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [88]:
# It returns the tuple after finding elements according to condition 
type(np.where(myarr4>5))

tuple

Count all nonzero Elements from Array

In [89]:
# To count the non zeros elements in an array
np.count_nonzero(myarr4)

9